apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: resident-marsupial-python 
  janus-idp.io/tekton: resident-marsupial-python
  backstage.io/kubernetes-id: resident-marsupial-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: resident-marsupial-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  